### ISSUE TITLE
Add macros for implementing algebraic traits less boilerplaty

### ISSUE THREAD

**Issue by WaDelma** [sebcrozet/alga#1]
Here is example code of the macros:
https://play.rust-lang.org/?gist=584830a89044aca1a59be9e310b02fb5&version=stable&backtrace=0

It doesn't include implementing identity or inverse yet. Also making it to create quickcheck test cases would be good.

**Comment by sebcrozet** [comment]
That's a good start. Now the hard part is to make those macros work with parametrized types as well. For example we need to be able to write something like: `impl_group!(Vector3<N: Group>)` or `impl_group!(VectorN<N: Group, D: ArrayLength>`

**Comment by WaDelma** [comment]
I made the macro to work with parametrized types, but it for it to work you need new enough nightly for some reason (Haven't figured what is the exact pr that fixes it). Problem is that `quickcheck_macro`s doesn't work that new nightly.
