### ISSUE TITLE
Add prelude

### ISSUE THREAD

**Issue by WaDelma** [sebcrozet/alga#13]
Adding prelude so that usual usage of alga would look like this would be useful:
````
extern crate alga;
use alga::prelude::*
````

**Comment by sebcrozet** [comment]
Well, the user can currently do `use alga::general::*` or `use alga::geometry::*`.
I'm worried that importing a single prelude might end up being too heavy when alga will have more features from other fields of algebra. With the current option, the user that is not interested by geometry does not have to import all the geometric traits.

**Comment by WaDelma** [comment]
Hmm.. Yeah that makes sense. Lets do it that way then :D
