### ISSUE TITLE
Deprecate macro_rules based deriving

### ISSUE THREAD

**Issue by WaDelma** [sebcrozet/alga#22]
As there now is custom derive based solution `macro_rules` based one isn't nessary.

Only thing that `macro_rules` based one allows that custom derive doesn't is to implement the trait for types not in current crate. Because how orphan rules work this is only relevant to `alga` itself.

So I propose removing `#[macro_export]` from all of the macros.

**Comment by brendanzab** [comment]
Do the custom derive attributes work on Rust stable?

**Comment by WaDelma** [comment]
Yes, custom derive attributes were stabilised so that serde and diesel can work in stable.
