### ISSUE TITLE
How to get MAX and MIN of a Real

### ISSUE THREAD

**Issue by orhanbalci** [sebcrozet/alga#33]
Hi there.
I could not find any place to ask for this. Please excuse me for the question. How can I get MIN or MAX of a Real?

**Comment by WaDelma** [comment]
Anything that is `Real` also implements [`Bounded`](https://docs.rs/num/0.1.40/num/trait.Bounded.html) which allows you to get the minimum and maximum value.

**Comment by orhanbalci** [comment]
Thanks for the answer
