### ISSUE TITLE
Help implementing `Scalar` for dual number

### ISSUE THREAD

**Issue by ChristopherRabotin** [sebcrozet/alga#43]
I'm seeking help in implementing the Scalar trait for [dual numbers](https://en.wikipedia.org/wiki/Dual_number), specifically for the [dual_num](https://github.com/novacrazy/dual_num) crate (which is currently undergoing an upgrade to support automatic partial derivatives). Please correct me if I'm wrong, but I think that mathematically, a dual number is indeed scalar (in the case of dual_num it is _represented_ as a `na::Vector2` but that should not alter its mathematical properties).

The purpose for implementing `Scalar` for dual number is to greatly simplify mathematical operations when using dual numbers in conjunction with the `nalgebra` crate.

Thanks for the support

P.S.: I think that these dual numbers could be represented in a similar fashion to how `Vec2<Scalar>` is represented in this [example](https://github.com/sebcrozet/alga/blob/master/alga/examples/vectors.rs#L17). I'll try that out.

**Comment by sebcrozet** [comment]
Are you referring to the `Scalar` trait from nalgebra [there](http://nalgebra.org/rustdoc/nalgebra/base/trait.Scalar.html)? If so, it is automatically implemented for any type that already implements `Copy + PartialEq + Debug + Any`.

**Comment by ChristopherRabotin** [comment]
Yes, I am referring to that `Scalar` trait.

Allow me to get to the details. I'd like to be able to multiply vectors of `Dual<T: Scalar+Num>`, but I currently cannot seem to be able to do this (note that the following code requires the latest `master` from [dual_num](https://github.com/novacrazy/dual_num) which isn't published on crates.io yet):

```
let x = Vector2::new(Dual::from(1.0f64), Dual::from(-2.0f64));
println!("{}", Dual::from(2.0f64) * x);
```

Which leads to the following error:
```
Compiling dual_num v0.2.0 (file:///home/chris/Workspace/rust/dual_num)
error[E0277]: cannot multiply `na::Matrix<dual_num::Dual<f64>, na::U2, na::U1, na::MatrixArray<dual_num::Dual<f64>, na::U2, na::U1>>` to `dual_num::Dual<f64>`
   --> tests/lib.rs:247:39
    |
247 |     println!("{}", Dual::from(2.0f64) * x);
    |                                       ^ no implementation for `dual_num::Dual<f64> * na::Matrix<dual_num::Dual<f64>, na::U2, na::U1, na::MatrixArray<dual_num::Dual<f64>, na::U2, na::U1>>`
    |
    = help: the trait `std::ops::Mul<na::Matrix<dual_num::Dual<f64>, na::U2, na::U1, na::MatrixArray<dual_num::Dual<f64>, na::U2, na::U1>>>` is not implemented for `dual_num::Dual<f64>`

error: aborting due to previous error
```

So I _assumed_, perhaps incorrectly, that the `Scalar` trait wasn't implemented because from the following code, I think that PartialEq, Debug and Copy are all implemented.

Note that the `Dual` struct is defined as follows:
```
#[derive(Clone, Copy)]
pub struct Dual<T: Scalar>(na::Vector2<T>);
/// ...
impl<T: Scalar + PartialEq> PartialEq<Self> for Dual<T> {
    fn eq(&self, rhs: &Self) -> bool {
        self.0 == rhs.0
    }
}
// ...
impl<T: Scalar + PartialEq> PartialEq<T> for Dual<T> {
    fn eq(&self, rhs: &T) -> bool {
        *self.real_ref() == *rhs
    }
}
/// ...
impl<T: Scalar> Debug for Dual<T> {
    fn fmt(&self, f: &mut Formatter) -> FmtResult {
        f.debug_tuple("Dual").field(self.real_ref()).field(self.dual_ref()).finish()
    }
}
```

Any hint is appreciated, thanks

**Comment by ChristopherRabotin** [comment]
For the record:
The solution was trivial (as pointed out by sebcrozet on IRC). The scalar multiplication of a vector must be as `vector * x` due to the limitations of the compilers (which prevents implementing traits on structs defined by other traits).

Thanks for the support!
